openapi: 3.0.1
info:
  title: exporter-trigger
  description: Service that responsible for activating the export geopackage process
  version: 2.20.4
  license:
    name: MIT
    url: https://opensource.org/licenses/MIT
paths:
  /storage:
    get:
      tags:
        - storage
      summary: Get free and total storage size for exporting (in bytes)
      operationId: getStorage
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/StorageResponse'
        '500':
          description: Internal Server Error
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/internalError'
  /export:
    post:
      tags:
        - createGpkg
      summary: >-
        Trigger export geopackages based on providing Regions of interest
        (multi-resolution)
      operationId: byRoi
      requestBody:
        $ref: '#/components/requestBodies/ExportByRoiBody'
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                oneOf:
                  - $ref: '#/components/schemas/createExportJobResponse'
                  - $ref: '#/components/schemas/exportNaiveCacheJobResponse'
                discriminator:
                  propertyName: response
        '400':
          description: Bad Request
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/error'
        '404':
          description: Could not find layer with matched dbId
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/error'
        '409':
          description: Duplicate Export Request
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/error'
        '500':
          description: Internal Server Error
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/internalError'
        '507':
          description: Insufficient Storage on disk for exporting
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/error'
  /tasks/taskStatus/{jobId}:
    get:
      tags:
        - tasks
      summary: Get task status by job id
      operationId: getTaskStatusByJobId
      parameters:
        - name: jobId
          in: path
          required: true
          schema:
            type: string
            format: uuid
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/getTaskStatusResponse'
        '400':
          description: Bad Request
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/error'
        '404':
          description: Could not find task with matched jobId
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/error'
        '500':
          description: Internal Server Error
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/internalError'
components:
  requestBodies:
    ExportByRoiBody:
      description: Export to gpkg via FeatureCollection
      required: true
      content:
        application/json:
          schema:
            $ref: '#/components/schemas/exportFromFeatures'
  schemas:
    StorageResponse:
      type: object
      description: Response for storage request (in bytes)
      required:
        - free
        - size
      properties:
        free:
          type: number
        size:
          type: number
    CommonResponse:
      type: object
      required:
        - status
      properties:
        status:
          type: string
          enum:
            - In-Progress
            - Completed
            - Pending
      discriminator:
        propertyName: response
    exportFromFeatures:
      type: object
      properties:
        dbId:
          type: string
          format: uuid
          description: ID as the primary key from the Raster Catalog
        roi:
          $ref: '#/components/schemas/FeatureCollection'
        callbackURLs:
          type: array
          items:
            type: string
          description: The callback URL to notify the process if finished
        crs:
          $ref: '#/components/schemas/CRS'
        priority:
          type: number
          description: The priority of the record. Maximum priority = most urgent.
          minimum: 0
          maximum: 999999999
        description:
          type: string
          description: free test to describe the requested export
      required:
        - dbId
      example:
        dbId: ef03ca54-c68e-4ca8-8432-50ae5ad7a7f8
        roi:
          type: FeatureCollection
          features:
            - type: Feature
              properties:
                maxResolutionDeg: 0.0439453125
                minResolutionDeg: 0.17578125
              geometry:
                type: Polygon
                coordinates:
                  - - - 34.82836896556114
                      - 32.03918441418732
                    - - 34.81210152170695
                      - 32.03918441418732
                    - - 34.81210152170695
                      - 32.02539369969462
                    - - 34.82836896556114
                      - 32.02539369969462
                    - - 34.82836896556114
                      - 32.03918441418732
        callbackURLs:
          - http://example.getmap.com/callback
          - http://example.getmap.com/callback2
        crs: EPSG:4326
        priority: 0
        description: This is roi exporting example
    createGpkgJobResponse:
      allOf:
        - $ref: '#/components/schemas/CommonResponse'
      type: object
      properties:
        id:
          type: string
          format: uuid
        taskIds:
          type: array
          items:
            type: string
            format: uuid
      required:
        - id
        - taskIds
    createExportJobResponse:
      allOf:
        - $ref: '#/components/schemas/CommonResponse'
      type: object
      properties:
        jobId:
          type: string
          format: uuid
        taskIds:
          type: array
          items:
            type: string
            format: uuid
        isDuplicated:
          type: boolean
      required:
        - jobId
        - taskIds
    naiveCacheJobResponse:
      allOf:
        - $ref: '#/components/schemas/CommonResponse'
      type: object
      properties:
        status:
          type: string
          enum:
            - Completed
        fileUri:
          type: string
        expirationTime:
          type: string
          format: date
        fileSize:
          type: number
        dbId:
          type: string
          format: uuid
        packageName:
          type: string
        bbox:
          oneOf:
            - $ref: '#/components/schemas/BBox'
            - $ref: '#/components/schemas/Geometry'
        targetResolution:
          type: number
        requestId:
          type: string
        success:
          type: boolean
        errorReason:
          type: string
      required:
        - fileUri
        - expirationTime
        - fileSize
        - dbId
        - packageName
        - bbox
        - targetResolution
        - requestId
        - success
    exportNaiveCacheJobResponse:
      allOf:
        - $ref: '#/components/schemas/CommonResponse'
      type: object
      properties:
        links:
          $ref: '#/components/schemas/callbackLinks'
        expirationTime:
          type: string
          format: date
        fileSize:
          type: number
        recordCatalogId:
          type: string
          format: uuid
        description:
          type: string
        roi:
          $ref: '#/components/schemas/FeatureCollection'
        jobId:
          type: string
          format: uuid
        errorReason:
          type: string
      required:
        - links
        - expirationTime
        - fileSize
        - recordCatalogId
        - roi
        - jobId
        - status
    error:
      type: object
      required:
        - message
      properties:
        message:
          type: string
    internalError:
      type: object
      required:
        - message
        - stacktrace
      properties:
        message:
          type: string
        stacktrace:
          type: string
    CRS:
      type: string
      description: List of supported
      enum:
        - EPSG:4326
    Feature:
      required:
        - type
        - properties
        - geometry
      properties:
        type:
          type: string
          enum:
            - Feature
        properties:
          type: object
          required:
            - maxResolutionDeg
          properties:
            maxResolutionDeg:
              type: number
              minimum: 3.35276126861572e-7
              maximum: 0.703125
              format: double
              description: max resolution of layer in degrees/pixel
            minResolutionDeg:
              type: number
              minimum: 3.35276126861572e-7
              maximum: 0.703125
              format: double
              description: min resolution of layer in degrees/pixel
        geometry:
          type: object
          nullable: true
          oneOf:
            - $ref: '#/components/schemas/GeometryCollection'
            - $ref: '#/components/schemas/Geometry'
        bbox:
          $ref: '#/components/schemas/BBox'
    FeatureCollection:
      type: object
      description: GeoJson Feature collection
      required:
        - type
        - features
      properties:
        type:
          type: string
          enum:
            - FeatureCollection
        features:
          type: array
          items:
            $ref: '#/components/schemas/Feature'
        bbox:
          $ref: '#/components/schemas/BBox'
    BBox:
      type: array
      items:
        type: number
      minItems: 4
      maxItems: 4
      description: >-
        Bounding box corners (lower left, upper right)=[minx,miny,maxx,maxy] in
        crs units as array. If empty - original layer's bbox is taken.
    getTaskStatusResponse:
      type: object
      properties:
        percentage:
          type: number
          minimum: 0
          maximum: 100
          description: percentage of task by job id
        status:
          type: string
          enum:
            - Completed
            - In-Progress
            - Pending
            - Failed
            - Expired
            - Aborted
    GeometryCollection:
      type: object
      description: GeoJSon geometry collection
      required:
        - type
        - geometries
      externalDocs:
        url: http://geojson.org/geojson-spec.html#geometrycollection
      properties:
        type:
          type: string
          enum:
            - GeometryCollection
          description: custom properties
        geometries:
          type: array
          items:
            $ref: '#/components/schemas/GeometryBase'
    Geometry:
      description: GeoJSon geometry
      type: object
      oneOf:
        - $ref: '#/components/schemas/Polygon'
        - $ref: '#/components/schemas/MultiPolygon'
    Polygon:
      type: object
      description: GeoJSon geometry
      externalDocs:
        url: http://geojson.org/geojson-spec.html#id4
      allOf:
        - $ref: '#/components/schemas/GeometryBase'
        - properties:
            coordinates:
              type: array
              items:
                type: array
                items:
                  $ref: '#/components/schemas/Point2D'
    MultiPolygon:
      type: object
      description: GeoJSon geometry
      externalDocs:
        url: http://geojson.org/geojson-spec.html#id6
      allOf:
        - $ref: '#/components/schemas/GeometryBase'
        - properties:
            coordinates:
              type: array
              items:
                type: array
                items:
                  type: array
                  items:
                    $ref: '#/components/schemas/Point2D'
    GeometryBase:
      type: object
      description: GeoJSon geometry
      required:
        - type
      externalDocs:
        url: http://geojson.org/geojson-spec.html#geometry-objects
      properties:
        type:
          type: string
          enum:
            - Polygon
            - MultiPolygon
          description: the geometry type
    callbackLinks:
      type: object
      description: gpkg links - the geoPackage + metadata.json
      required:
        - dataURI
        - metadataURI
      properties:
        dataURI:
          type: string
          description: Url to download the gpkg
        metadataURI:
          type: string
          description: Url to download the gpkg's metadata.json
    Point2D:
      type: array
      maxItems: 2
      minItems: 2
      items:
        type: number
    Point:
      type: object
      description: GeoJSon geometry
      externalDocs:
        url: http://geojson.org/geojson-spec.html#id2
      allOf:
        - $ref: '#/components/schemas/GeometryBase'
        - properties:
            coordinates:
              $ref: '#/components/schemas/Point2D'
