{{- $chartName := include "exporter-trigger.name" . -}}
{{- $tracing := (include "common.tracing.merged" .) | fromYaml }}
{{- $metrics := (include "common.metrics.merged" .) | fromYaml }}
{{- $serviceUrls := (include "common.serviceUrls.merged" .) | fromYaml }}
{{- $storage := (include "common.storage.merged" .) | fromYaml }}
{{- $configmapName := include "configmap.fullname" . }}
{{- $jobDefinitions := (include "common.jobDefinitions.merged" .) | fromYaml }}


{{- if .Values.enabled -}}
apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ $configmapName }}
data:
  REQUEST_PAYLOAD_LIMIT: {{ .Values.env.requestPayloadLimit | quote }}
  RESPONSE_COMPRESSION_ENABLED: {{ .Values.env.responseCompressionEnabled | quote }}
  LOG_LEVEL: {{ .Values.env.logLevel | quote }}
  LOG_PRETTY_PRINT_ENABLED: {{ .Values.env.logPrettyPrintEnabled | quote }}
  TELEMETRY_TRACING_ENABLED: {{ $tracing.enabled | quote }}
  {{ if $tracing.enabled }}
  TELEMETRY_TRACING_URL: {{ $tracing.url }}
  {{ end }}
  TELEMETRY_METRICS_ENABLED: {{ $metrics.enabled | quote }}
  {{ if $metrics.enabled}}
  TELEMETRY_METRICS_URL: {{ $metrics.url }}
  {{ end }}
  JOB_MANAGER_URL: {{ $serviceUrls.jobManager | quote }}
  CLEANUP_EXPIRATION_DAYS: {{ .Values.env.cleanupExpirationDays | quote }}
  RASTER_CATALOG_MANAGER_URL: {{ $serviceUrls.catalogManager | quote }}
  JOB_DOMAIN: {{ .Values.global.domain | quote }}
  EXPORT_JOB_TYPE: {{ $jobDefinitions.jobs.export.type | quote }}
  HTTP_RETRY_ATTEMPTS: {{ .Values.env.httpRetry.attempts | quote }}
  HTTP_RETRY_DELAY: {{ .Values.env.httpRetry.delay | quote }}
  HTTP_RETRY_SHOULD_RESET_TIMEOUT: {{ .Values.env.httpRetry.shouldResetTimeout | quote }}
  DISABLE_HTTP_CLIENT_LOGS: {{ .Values.env.disableHttpClientLogs | quote }}
  TILES_PROVIDER: {{ $storage.tilesStorageProvider | quote }}
  DOWNLOAD_SERVER_PUBLIC_DNS: {{ $serviceUrls.downloadServerPublicDNS | quote }}
  JPEG_TILE_ESTIMATED_SIZE_IN_BYTES: {{ .Values.env.estimatedStorageCalculation.jpegTileEstimatedSizeInBytes | quote }}
  PNG_TILE_ESTIMATED_SIZE_IN_BYTES: {{ .Values.env.estimatedStorageCalculation.pngTileEstimatedSizeInBytes | quote }}
  STORAGE_FACTOR_BUFFER: {{ .Values.env.estimatedStorageCalculation.storageFactorBuffer | quote }}
  INIT_TASK_TYPE: {{ $jobDefinitions.tasks.init.type | quote }}
  ROI_BUFFER_METER: {{ .Values.env.roiBufferMeter | quote }}
  MIN_CONTAINED_PERCENTAGE: {{ .Values.env.minContainedPercentage | quote }}
{{- end }}
