{{- $releaseName := .Release.Name -}}
{{- $chartName := include "exporter-trigger.name" . -}}
{{- $cloudProviderFlavor := include "exporter-trigger.cloudProviderFlavor" . -}}
{{- $serviceName := include "service.fullname" . -}}
{{- $routeName := include "route.fullname" . }}
{{- if and (and (.Values.enabled) (eq $cloudProviderFlavor "openshift")) (.Values.route.enabled) -}}
apiVersion: route.openshift.io/v1
kind: Route
metadata:
  name: {{ $routeName }}
  annotations:
    haproxy.router.openshift.io/rewrite-target: /
    {{- if .Values.route.timeout.enabled }}
    haproxy.router.openshift.io/timeout: {{ .Values.route.timeout.duration }}
    {{- end }}
spec:
  {{- if .Values.route.host }}
  host: {{ .Values.route.host }}
  {{- end }}
  path:  {{ .Values.route.path | default "/" }}
  to:
    kind: Service
    name: {{ $serviceName }}
  {{- if .Values.route.https }}
  tls:
    termination: edge
    insecureEdgeTerminationPolicy: Redirect
  {{- end -}}
{{- end -}}
